apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/rata-live-chat-ui

namespace: rata-dynamic

images:
  - name: registry.rata.id/rata-live-chat-ui
    newName: registry.rata.id/rata-live-chat-ui
    newTag: placeholder