apiVersion: v1
kind: Service
metadata:
  name: crm
  namespace: rata-dynamic
  labels:
    app: rata-live-chat
    service: crm
spec:
  type: ClusterIP
  selector:
    app: rata-live-chat
    service: crm
  ports:
    - port: 80
      targetPort: 80