export const PAGINATION_TABLE_PERPAGES = [5, 10, 20, 50, 100]

export const PAGINATION_TABLE_PERPAGE = PAGINATION_TABLE_PERPAGES[1]

export const PAGINATION_TABLE_ORDER_CUSTOMER_PERPAGES = [2, 4, 6, 8, 10]

export const PAGINATION_TABLE_ORDER_CUSTOMER_PERPAGE =
  PAGINATION_TABLE_ORDER_CUSTOMER_PERPAGES[1]

export const PAGINATION_CARD_PERPAGES = [8, 12, 24, 48, 96]

export const PAGINATION_CARD_PERPAGE = PAGINATION_CARD_PERPAGES[1]

export const PAGINATION_INITIAL_STATE = {
  args: null,
  arrArgs: [],
  currentPage: 1,
  searchQuery: '',
  perPage: PAGINATION_TABLE_PERPAGE,
}
