export * from './logo-smiledental'
export * from './logo-clinics'
export * from './logo-rata'
export * from './logo-tanam'
export * from './logo-vinir'
export * from './icon-history'
export * from './icon-book-open-text'
export * from './avatar-placeholder'
