query AllPermissions(
  $where: PermissionWhereInput
  $orderBy: [PermissionOrderByWithRelationInput!]
  $cursor: PermissionWhereUniqueInput
  $take: Int
  $skip: Int
) {
  allPermissions(
    where: $where
    orderBy: $orderBy
    cursor: $cursor
    take: $take
    skip: $skip
  ) {
    id
    code
    group
    action
  }
}
