query Permissions(
  $where: PermissionWhereInput
  $orderBy: [PermissionOrderByWithRelationInput!]
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  permissions(
    where: $where
    orderBy: $orderBy
    first: $first
    after: $after
    last: $last
    before: $before
  ) {
    nodes {
      id
      group
      action
    }
    totalCount
    totalPages
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
