query User($id: Cuid!) {
  user(id: $id) {
    id
    name
    phone
    email
    notes
    isActive
    userRoles(orderBy: { createdAt: asc }) {
      id
      role {
        id
        title
        abbr
      }
    }
  }
}
