query Users(
  $where: UserWhereInput
  $orderBy: [UserOrderByWithRelationInput!]
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  users(
    where: $where
    orderBy: $orderBy
    first: $first
    after: $after
    last: $last
    before: $before
  ) {
    nodes {
      id
      name
      phone
      email
      notes
      isActive
    }
    totalCount
    totalPages
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
